#line drawing

seq_len: 20
training_size: 1000
test_size: 1000
train_val_split: 0.2
fixdata: False
train_noise_var: 0.1
test_noise_var: 0.1
input_D: 10
npoints: 6
mag: 1
arc: 0
equal_spacing: False 

